### ISSUE TITLE
Requesting Contact (Unrelated)

### ISSUE THREAD

**Issue by ryan-v1** [Vexrax/DiscordBot-Rust#1]
Hi Josh,

For the past two years i've been trying to replicate a very specific feature from one of your projects. This feature is driving me absolutely insane & after hundreds of hours, I still have no clue how you've done it.

I know time is valuable but I would rather have this conversation over discord. If you have a moment, please add me, the username is **ryan.tf**. 

From developer to another developer, please help before I lose all of my sanity. It's such a stupid & relatively small thing as well, but it affects the public perception of my work by so much.

**Comment by Vexrax** [comment]
Hi Ryan, 
Unfortunately i dont give out my personal discord. However feel free to ask any questions you have on this open ticket and ill be happy to help you!

**Comment by ryan-v1** [comment]
Hi, thanks for the quick response :)

Due to the nature of what i'm going to ask, i'd rather not have the conversation out & in the open. Are you still active on https://twitter.com/__Dueces__ by any chance? If you're willing I can just send a dm there but I thought you were inactive lol

**Comment by Vexrax** [comment]
That account is mostly inactive too. If your question is code specific, I would rather have the question asked in the open so that if others have similar issues they will be able to find the solution. Its likely that your question may save other devs time in the future.
